language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: dce910939e7d031cac65097a3cffadf0084187e8
 local_dir: dist
 on:
   branch: master